// const urls = [
// 'https://parimatch.com/sport/futbol/anglija-premer-liga-statistika',
// 'https://parimatch.com/sport/futbol/anglija-kubok-ligi',
// 'https://parimatch.com/sport/futbol/germanija-kubok',
// 'https://parimatch.com/sport/futbol/germanija-kubok-statistika',
// 'https://parimatch.com/sport/futbol/ispanija-superkubok-statistika',
// 'https://parimatch.com/sport/futbol/italija-kubok',
// 'https://parimatch.com/sport/futbol/italija-kubok-statistika',
// 'https://parimatch.com/sport/futbol/niderlandy-eredivisie-statistika',
// 'https://parimatch.com/sport/futbol/rossija-premer-liga',
// 'https://parimatch.com/sport/futbol/rossija-kubok',
// 'https://parimatch.com/sport/futbol/ukraina-kubok',
// 'https://parimatch.com/sport/futbol/francija-superkubok-statistika',
// 'https://parimatch.com/sport/futbol/kubok-libertadores',
// 'https://parimatch.com/sport/futbol/kluby-tovarishheskie-matchi',
// 'https://parimatch.com/sport/futbol/anglija-trofejj-futbolnojj-associacii',
// 'https://parimatch.com/sport/futbol/anglija-liga-1',
// 'https://parimatch.com/sport/futbol/anglija-liga-2',
// 'https://parimatch.com/sport/futbol/anglija-pdl',
// 'https://parimatch.com/sport/futbol/anglija-trofejj-afl',
// 'https://parimatch.com/sport/futbol/belgija-pervyjj-divizion-a-statistika',
// 'https://parimatch.com/sport/futbol/germanija-bundesliga-2',
// 'https://parimatch.com/sport/futbol/germanija-liga-3',
// 'https://parimatch.com/sport/futbol/grecija-superliga-1-statistika',
// 'https://parimatch.com/sport/futbol/ispanija-segunda-b',
// 'https://parimatch.com/sport/futbol/ispanija-tersera',
// 'https://parimatch.com/sport/futbol/ispanija-chempionat-u-19',
// 'https://parimatch.com/sport/futbol/italija-serija-b',
// 'https://parimatch.com/sport/futbol/italija-serija-c',
// 'https://parimatch.com/sport/futbol/italija-serija-d',
// 'https://parimatch.com/sport/futbol/kipr-divizion-1',
// 'https://parimatch.com/sport/futbol/malta-premer-liga',
// 'https://parimatch.com/sport/futbol/niderlandy-pervyjj-divizion',
// 'https://parimatch.com/sport/futbol/portugalija-kubok',
// 'https://parimatch.com/sport/futbol/portugalija-segunda',
// 'https://parimatch.com/sport/futbol/portugalija-nacionalnyjj-chempionat',
// 'https://parimatch.com/sport/futbol/rumynija-liga-1',
// 'https://parimatch.com/sport/futbol/turcija-liga-2',
// 'https://parimatch.com/sport/futbol/turcija-liga-3',
// 'https://parimatch.com/sport/futbol/turcija-kubok',
// 'https://parimatch.com/sport/futbol/francija-liga-2',
// 'https://parimatch.com/sport/futbol/francija-nacionalnyjj-divizion',
// 'https://parimatch.com/sport/futbol/chekhija-pervaja-liga',
// 'https://parimatch.com/sport/futbol/chekhija-zimnjaja-liga',
// 'https://parimatch.com/sport/futbol/shotlandija-liga-1',
// 'https://parimatch.com/sport/futbol/shotlandija-liga-2',
// 'https://parimatch.com/sport/futbol/juzhnoamerikanskijj-kubok',
// 'https://parimatch.com/sport/futbol/argentina-kubok-ligi',
// 'https://parimatch.com/sport/futbol/argentina-primera-c-metropolitana',
// 'https://parimatch.com/sport/futbol/brazilija-serija-a',
// 'https://parimatch.com/sport/futbol/brazilija-serija-v',
// 'https://parimatch.com/sport/futbol/brazilija-liga-gojanu-divizion-1',
// 'https://parimatch.com/sport/futbol/brazilija-liga-karioka-serija-b2',
// 'https://parimatch.com/sport/futbol/kolumbija-primera-a',
// 'https://parimatch.com/sport/futbol/kolumbija-kubok',
// 'https://parimatch.com/sport/futbol/urugvajj-primera-divizion',
// 'https://parimatch.com/sport/futbol/chili-primera-divizion',
// 'https://parimatch.com/sport/futbol/chili-primera-v',
// 'https://parimatch.com/sport/futbol/kosta-rika-primera-divizion',
// 'https://parimatch.com/sport/futbol/meksika-liga-mx',
// 'https://parimatch.com/sport/futbol/meksika-liga-de-expansion-mx',
// 'https://parimatch.com/sport/futbol/salvador-primera-divizion',
// 'https://parimatch.com/sport/futbol/salvador-rezervnaja-liga',
// 'https://parimatch.com/sport/futbol/bangladesh-premer-liga',
// 'https://parimatch.com/sport/futbol/indija-superliga',
// 'https://parimatch.com/sport/futbol/indija-superliga-statistika',
// 'https://parimatch.com/sport/futbol/indija-i-liga',
// 'https://parimatch.com/sport/futbol/indija-bangalor-super-divizion',
// 'https://parimatch.com/sport/futbol/iordanija-pro-liga',
// 'https://parimatch.com/sport/futbol/iordanija-pervyjj-divizion',
// 'https://parimatch.com/sport/futbol/iran-divizion-2',
// 'https://parimatch.com/sport/futbol/katar-starz-liga',
// 'https://parimatch.com/sport/futbol/katar-vtorojj-divizion',
// 'https://parimatch.com/sport/futbol/oman-premer-liga',
// 'https://parimatch.com/sport/futbol/saudovskaja-aravija-pro-liga',
// 'https://parimatch.com/sport/futbol/saudovskaja-aravija-divizion-1',
// 'https://parimatch.com/sport/futbol/alzhir-liga-1',
// 'https://parimatch.com/sport/futbol/gambija-divizion-2',
// 'https://parimatch.com/sport/futbol/egipet-premer-liga',
// 'https://parimatch.com/sport/futbol/egipet-vtorojj-divizion',
// 'https://parimatch.com/sport/futbol/zambija-premer-liga',
// 'https://parimatch.com/sport/futbol/kenija-premer-liga',
// 'https://parimatch.com/sport/futbol/kenija-superliga',
// 'https://parimatch.com/sport/futbol/mavritanija-chempionat',
// 'https://parimatch.com/sport/futbol/nigerija-premer-liga',
// 'https://parimatch.com/sport/futbol/tunis-liga-1',
// 'https://parimatch.com/sport/futbol/juar-psl',
// 'https://parimatch.com/sport/futbol/avstralija-a-liga',
// 'https://parimatch.com/sport/futbol/zhenshhiny-avstralija-w-liga',
// 'https://parimatch.com/sport/futbol/zhenshhiny-anglija-kubok-ligi',
// 'https://parimatch.com/sport/futbol/zhenshhiny-argentina-primera-b',
// 'https://parimatch.com/sport/futbol/zhenshhiny-ispanija-superkubok',
// 'https://parimatch.com/sport/futbol/zhenshhiny-italija-kubok',
// 'https://parimatch.com/sport/futbol/zhenshhiny-meksika-liga-mkh',
// 'https://parimatch.com/sport/futbol/zhenshhiny-portugalija-nacionalnyjj-chempionat',
// 'https://parimatch.com/sport/futbol/brazilija-kubok-faresa-lopesa',
// 'https://parimatch.com/sport/futbol/ispanija-superkubok',

// ];

const urls = [
  'https://parimatch.com/sport/futbol/anglija-premer-liga',
  'https://parimatch.com/sport/futbol/polsha-ekstraklasa',
  'https://parimatch.com/sport/futbol/liga-evropy-uefa-plejj-off',
  'https://parimatch.com/sport/futbol/liga-chempionov-uefa-plejj-off',
  'https://parimatch.com/sport/futbol/belgija-pervyjj-divizion-a',
  'https://parimatch.com/sport/futbol/chempionat-evropy-gruppovojj-ehtap',
  'https://parimatch.com/sport/futbol/liga-nacijj-uefa-liga-a',
  'https://parimatch.com/sport/futbol/germanija-bundesliga',
  'https://parimatch.com/sport/futbol/ispanija-primera',
  // 'https://parimatch.com/sport/futbol/ispanija-kubok-korolja',
  // 'https://parimatch.com/sport/futbol/italija-superkubok',
  'https://parimatch.com/sport/futbol/italija-serija-a',
  'https://parimatch.com/sport/futbol/niderlandy-eredivisie',
  'https://parimatch.com/sport/futbol/portugalija-primejjra-liga',
  // 'https://parimatch.com/sport/futbol/francija-superkubok',
  'https://parimatch.com/sport/futbol/francija-liga-1',
  'https://parimatch.com/sport/futbol/turcija-superliga',
  'https://parimatch.com/sport/futbol/shotlandija-premership',
  'https://parimatch.com/sport/futbol/danija-superliga',
  'https://parimatch.com/sport/futbol/avstrija-bundesliga',
  // 'https://parimatch.com/sport/futbol/shotlandija-chempionship',
  'https://parimatch.com/sport/futbol/anglija-chempionship',
  'https://parimatch.com/sport/futbol/grecija-superliga-1',
  'https://parimatch.com/sport/futbol/khorvatija-liga-1'
];
module.exports = urls;
