// const urls = [
// "https://www.marathonbet.com/uk/betting/Football/England/League+Cup/Final/London+-+742054",
// "https://www.marathonbet.com/uk/betting/Football/Germany/Cup/2nd+Round+-+437598",
// "https://www.marathonbet.com/uk/betting/Football/Italy/Cup/Round+of+16+-+564164",
// "https://www.marathonbet.com/uk/betting/Football/Clubs.+International/Copa+Libertadores/Semi+Final/2nd+Leg+-+170091",
// "https://www.marathonbet.com/uk/betting/Football/Clubs.+International/Sudamericana+Cup/Semi+Final/2nd+Leg+-+302047",
// "https://www.marathonbet.com/uk/betting/Football/Portugal/Cup/Round+of+16+-+969282",
// "https://www.marathonbet.com/uk/betting/Football/Russia/Premier+League+-+22433",
// "https://www.marathonbet.com/uk/betting/Football/Turkey/Cup/Round+of+16+-+969035",
// "https://www.marathonbet.com/uk/betting/Football/Denmark/Cup/Quarter+Final/1st+Leg+-+10819737",
// 'https://www.marathonbet.com/uk/betting/Football/Germany/Bundesliga+2+-+42528',
// 'https://www.marathonbet.com/uk/betting/Football/Italy/Serie+B+-+46723',
// 'https://www.marathonbet.com/uk/betting/Football/France/Ligue+2+-+46785'
// "https://www.marathonbet.com/uk/betting/Football/Australia/A-League+-+233682",
// "https://www.marathonbet.com/uk/betting/Football/Austria/2+Liga+-+6955819",
// "https://www.marathonbet.com/uk/betting/Football/Algeria/Ligue+1+-+549283",
// "https://www.marathonbet.com/uk/betting/Football/England/Professional+Development+League+2+U-23+-+4592372",
// "https://www.marathonbet.com/uk/betting/Football/England/League+1+-+22808",
// "https://www.marathonbet.com/uk/betting/Football/England/League+2+-+22809",
// "https://www.marathonbet.com/uk/betting/Football/England/FA+Trophy/4th+Round+-+356031",
// "https://www.marathonbet.com/uk/betting/Football/England/EFL+Trophy/Round+of+16+-+3581099",
// "https://www.marathonbet.com/uk/betting/Football/Argentina/Primera+C+Metropolitana/Group+Stage+-+10655313",
// "https://www.marathonbet.com/uk/betting/Football/Bangladesh/Premier+League/Dhaka+-+6228910",
// "https://www.marathonbet.com/uk/betting/Football/Brazil/Serie+A+-+211229",
// "https://www.marathonbet.com/uk/betting/Football/Brazil/Serie+B+-+386546",
// "https://www.marathonbet.com/uk/betting/Football/Brazil/Goiano/1st+Division+-+1679824",
// "https://www.marathonbet.com/uk/betting/Football/Brazil/Carioca/Serie+B2/Stage+2+-+7362903",
// "https://www.marathonbet.com/uk/betting/Football/Brazil/Fares+Lopes+Cup/Round+Robin+-+8421823",
// "https://www.marathonbet.com/uk/betting/Football/Brazil/Santa+Catarina+Cup/Group+Stage+-+7269528",
// "https://www.marathonbet.com/uk/betting/Football/Gambia/2nd+Division+-+7947805",
// "https://www.marathonbet.com/uk/betting/Football/Denmark/1st+Division+-+469386",
// "https://www.marathonbet.com/uk/betting/Football/Egypt/2nd+Division+-+542816",
// "https://www.marathonbet.com/uk/betting/Football/India/I-League+-+341094",
// "https://www.marathonbet.com/uk/betting/Football/India/Super+League+-+2328940",
// "https://www.marathonbet.com/uk/betting/Football/India/Bengaluru/Super+Division+-+434001",
// "https://www.marathonbet.com/uk/betting/Football/Spain/Segunda+Division+B/Group+2+-+561609",
// "https://www.marathonbet.com/uk/betting/Football/Spain/Segunda+Division+B/Group+3+-+511155",
// "https://www.marathonbet.com/uk/betting/Football/Spain/Tercera+Division/Group+5+-+593190",
// "https://www.marathonbet.com/uk/betting/Football/Spain/Tercera+Division/Group+6+-+593350",
// "https://www.marathonbet.com/uk/betting/Football/Spain/Tercera+Division/Group+8+-+564329",
// "https://www.marathonbet.com/uk/betting/Football/Spain/Tercera+Division/Group+18+-+590381",
// "https://www.marathonbet.com/uk/betting/Football/Spain/Division+de+Honor+Juvenil/Group+2+-+2758579",
// "https://www.marathonbet.com/uk/betting/Football/Spain/Division+de+Honor+Juvenil/Group+5+-+1545092",
// "https://www.marathonbet.com/uk/betting/Football/Spain/Division+de+Honor+Juvenil/Group+6+-+3490643",
// "https://www.marathonbet.com/uk/betting/Football/Spain/Division+de+Honor+Juvenil/Group+7+-+2273933",
// "https://www.marathonbet.com/uk/betting/Football/Italy/Serie+D+-+916779",
// "https://www.marathonbet.com/uk/betting/Football/Italy/Serie+C/Group+A+-+4511095",
// "https://www.marathonbet.com/uk/betting/Football/Italy/Serie+C/Group+B+-+4511096",
// "https://www.marathonbet.com/uk/betting/Football/Italy/Serie+C/Group+C+-+2075320",
// "https://www.marathonbet.com/uk/betting/Football/Jordan/1st+Division+-+949050",
// "https://www.marathonbet.com/uk/betting/Football/Qatar/Stars+League+-+544931",
// "https://www.marathonbet.com/uk/betting/Football/Kenya/Premier+League+-+849049",
// "https://www.marathonbet.com/uk/betting/Football/Kenya/Super+League+-+6539272",
// "https://www.marathonbet.com/uk/betting/Football/Cyprus/1st+Division+-+338996",
// "https://www.marathonbet.com/uk/betting/Football/Colombia/Cup/Quarter+Final+-+853918",
// "https://www.marathonbet.com/uk/betting/Football/Costa+Rica/Primera+Division+-+461301",
// "https://www.marathonbet.com/uk/betting/Football/Malta/Premier+League/Ta%27+Qali+-+7461500",
// "https://www.marathonbet.com/uk/betting/Football/Mexico/Primera+Division+-+223070",
// "https://www.marathonbet.com/uk/betting/Football/Mexico/Liga+de+Expansion+-+9994231",
// "https://www.marathonbet.com/uk/betting/Football/Nigeria/Professional+League+-+3280902",
// "https://www.marathonbet.com/uk/betting/Football/Netherlands/Eerste+Divisie+-+345004",
// "https://www.marathonbet.com/uk/betting/Football/Nicaragua/Segunda+Division/Play-Offs/Semi+Final/1st+Leg+-+10848057",
// "https://www.marathonbet.com/uk/betting/Football/Germany/3+Liga+-+432293",
// "https://www.marathonbet.com/uk/betting/Football/Oman/Professional+League+-+350419",
// "https://www.marathonbet.com/uk/betting/Football/South+Africa/Premier+League+-+574869",
// "https://www.marathonbet.com/uk/betting/Football/Portugal/Segunda+Liga+-+344256",
// "https://www.marathonbet.com/uk/betting/Football/Portugal/National+Championship+-+1916077",
// "https://www.marathonbet.com/uk/betting/Football/Romania/Liga+I+-+223112",
// "https://www.marathonbet.com/uk/betting/Football/El+Salvador/Primera+Division/Play-Offs/Quarter+Final/1st+Leg+-+3746188",
// "https://www.marathonbet.com/uk/betting/Football/El+Salvador/Reserve+League/Play-Offs/Quarter+Final/1st+Leg+-+4898469",
// "https://www.marathonbet.com/uk/betting/Football/Saudi+Arabia/Pro+League+-+528930",
// "https://www.marathonbet.com/uk/betting/Football/Saudi+Arabia/Division+1+-+480574",
// "https://www.marathonbet.com/uk/betting/Football/Tunisia/Ligue+1+-+352781",
// "https://www.marathonbet.com/uk/betting/Football/Turkey/2+Lig/White+Group+-+581517",
// "https://www.marathonbet.com/uk/betting/Football/Turkey/2+Lig/Red+Group+-+581279",
// "https://www.marathonbet.com/uk/betting/Football/Turkey/3+Lig/Group+4+-+10222086",
// "https://www.marathonbet.com/uk/betting/Football/Uruguay/Primera+Division/Intermediate+Round+-+5502947",
// "https://www.marathonbet.com/uk/betting/Football/France/National+-+345005",
// "https://www.marathonbet.com/uk/betting/Football/Czech+Republic/1st+League+-+46796",
// "https://www.marathonbet.com/uk/betting/Football/Czech+Republic/Winter+League/Group+Stage/Prague+-+2789264",
// "https://www.marathonbet.com/uk/betting/Football/Chile/Primera+Division+-+341825",
// "https://www.marathonbet.com/uk/betting/Football/Chile/Primera+B+-+747278",
// "https://www.marathonbet.com/uk/betting/Football/Switzerland/Super+League+-+46331",
// "https://www.marathonbet.com/uk/betting/Football/Friendlies/Clubs+-+420655",
// "https://www.marathonbet.com/uk/betting/Football/Friendly+Tournaments/Clubs/Medulin%2C+Croatia/Round+Robin+-+6450453",
// "https://www.marathonbet.com/uk/betting/Football/Women/Australia/W-League+-+505206",
// "https://www.marathonbet.com/uk/betting/Football/Women/England/Super+League+Cup/Quarter+Final+-+3334640",
// "https://www.marathonbet.com/uk/betting/Football/Women/Spain/Super+Cup/Semi+Final/Almeria+-+10842374",
// "https://www.marathonbet.com/uk/betting/Football/Women/El+Salvador/National+League/Play-Offs/Quarter+Final/1st+Leg+-+8816995",
// "https://www.marathonbet.com/uk/betting/Football/Outright/UEFA+Champions+League+-+211202",
// "https://www.marathonbet.com/uk/betting/Football/Outright/UEFA+Europa+League+-+211224",
// "https://www.marathonbet.com/uk/betting/Football/Outright/UEFA+Euro/2020+-+7055449",
// "https://www.marathonbet.com/uk/betting/Football/Outright/UEFA+Euro/2020/Groups.+Outright+-+8829498",
// "https://www.marathonbet.com/uk/betting/Football/Outright/Copa+America+-+3099187",
// "https://www.marathonbet.com/uk/betting/Football/Outright/UEFA+Nations+League+-+7164755",
// "https://www.marathonbet.com/uk/betting/Football/Outright/FIFA+World+Cup/2022+-+7051167",
// "https://www.marathonbet.com/uk/betting/Football/Outright/FIFA+World+Cup/2022/Qualification/Europe/Groups.+Outright+-+10662304",
// "https://www.marathonbet.com/uk/betting/Football/Outright/Copa+Libertadores+-+2058839",
// "https://www.marathonbet.com/uk/betting/Football/Outright/England+-+1507",
// "https://www.marathonbet.com/uk/betting/Football/Outright/Spain+-+7942",
// "https://www.marathonbet.com/uk/betting/Football/Outright/Italy+-+1871",
// "https://www.marathonbet.com/uk/betting/Football/Outright/Germany+-+8675",
// "https://www.marathonbet.com/uk/betting/Football/Outright/Russia+-+70509",
// "https://www.marathonbet.com/uk/betting/Football/Outright/France+-+7953",
// "https://www.marathonbet.com/uk/betting/Football/Outright/Scotland+-+1776"
// 'https://www.marathonbet.com/uk/betting/Football/Clubs.+International/UEFA+Europa+League/Play-Offs/Round+of+32/1st+Leg+-+120852',
// 'https://www.marathonbet.com/uk/betting/Football/Clubs.+International/UEFA+Champions+League/Play-Offs/Round+of+16/1st+Leg+-+120844',
// 'https://www.marathonbet.com/uk/betting/Football/Internationals/UEFA+Euro/2020/Final+Tournament/Group+Stage+-+7952550',
// 'https://www.marathonbet.com/uk/betting/Football/Internationals/UEFA+Nations+League/League+A/Final+Stage/Italy/Play-Offs/Semi+Final+-+10630636',
// 'https://www.marathonbet.com/uk/betting/Football/Spain/Cup/Round+of+32+-+516048',
// 'https://www.marathonbet.com/uk/betting/Football/Scotland/Premiership+-+22435',
// ];

const urls = [
  'https://www.marathonbet.com/uk/betting/Football/England/Premier+League+-+21520',
  'https://www.marathonbet.com/uk/betting/Football/Poland/Ekstraklasa+-+47116',
  'https://www.marathonbet.com/uk/betting/Football/Germany/Bundesliga+-+22436',
  'https://www.marathonbet.com/uk/betting/Football/Spain/Primera+Division+-+8736',
  'https://www.marathonbet.com/uk/betting/Football/Italy/Serie+A+-+22434',
  'https://www.marathonbet.com/uk/betting/Football/France/Ligue+1+-+21533',
  'https://www.marathonbet.com/uk/betting/Football/Portugal/Primeira+Liga+-+43058',
  'https://www.marathonbet.com/uk/betting/Football/Turkey/Super+Lig+-+46180',
  'https://www.marathonbet.com/uk/betting/Football/Netherlands/Eredivisie+-+38090',
  'https://www.marathonbet.com/uk/betting/Football/Belgium/1st+Division+A+-+46181',
  'https://www.marathonbet.com/uk/betting/Football/Denmark/Superliga+-+49330',
  'https://www.marathonbet.com/uk/betting/Football/Austria/Bundesliga+-+46715',
  'https://www.marathonbet.com/uk/betting/Football/Scotland/Championship+-+37771',
  'https://www.marathonbet.com/uk/betting/Football/England/Championship+-+22807',
  'https://www.marathonbet.com/uk/betting/Football/Greece/Super+League+-+46355',
  'https://www.marathonbet.com/uk/betting/Football/Croatia/1st+League+-+353647'
];
module.exports = urls;
